### ISSUE TITLE
ensure PCC db has timestamp fields for ...

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#106]
- storage_root to db 1:1 existence check 
- db to storage_root 1:1 existence check
- checksum validation
- any other specific validation checks as they come into play

**Comment by ndushay** [comment]
See also #98 -- if it's a dup, pull whatever over here and close it

**Comment by tallenaz** [comment]
From #98:

- 'last "inventory" existence check (from storage root to PCC)' == storage_root to db 1:1 existence check
- 'last "audit" existence check (from PCC to storage root)' == db to storage_root 1:1 existence check
- 'last "fixity" check' == checksum validation

**Comment by jmartin-sul** [comment]
after some discussion, the following fields will be added to the `preservation_copies` table:
`last_checked_on_storage`:  the last time the object was checked for on disk, regardless of whether it was found on disk
`last_checksum_validation`:  the last time the object contents were fixity checked, regardless of whether the check was passed.

we declined to add a field indicating when an object that was found on disk was last checked to see whether there was a corresponding entry in the DB.  the thinking being: this will never differ in value from the `updated_at` field, and is not actually semantically different.  if the object is there on disk, and there isn't an entry in the DB, we'll create one (and warn that it should've been in the inventory db already).  if there is an entry, we (activerecord) `#touch` the row (which sets `updated_at` to the current time).  if the entry was missing from the inventory db, there'd be nothing to query in the db anyway, and so no way to ask when that druid last had its catalog entry updated.

**Comment by ndushay** [comment]
pardon my ignorance here:  do we need to do anything different for "existence checks" for online moabs vs. archival copies?   ditto for checksum validation.  Also, I think Julian is cooking up some additional checks that we haven't heard about yet.  But we can deal with those later.

**Comment by jmartin-sul** [comment]
i'm not totally sure, but my guess is that at the level we're capturing in the DB, the broad categories of "last seen on disk" and "last checked for file integrity" will both be applicable to both online and archival copies.  probably with different policies per endpoint type for how stale we let those values get before we worry and alert, and how we schedule those checks in the first place?  and maybe more historical detail available via the (provenance) logs?
