### ISSUE TITLE
PCC: benchmark storage performance

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#11]
related to / blocked by #10:

For each of the types of reads and writes for the PCC, we will want to make sure our storage choice is performant:

- given the (large) quantity of data already in storage
- given the volume of read/write requests expected

Can think of this from perspective of:
- Trusted Checksum Repo
- Object Inventory
- Object Provenance

and/or from

- Audit process
  - Inventory process?
- Archive process
- Ingest process

**Comment by ndushay** [comment]
Julian is confident that we we can quickly write scripts to populate a postgres db, and also write scripts to hit it with to get benchmark data.

If it seems unacceptable, talk to Erin and/or Darren H for performance tuning advice.

(rather than spinning up multiple environments for this - just check the one we've started with, that may be adequate)

This *may* require a diff VM or some VM config tweaking (e.g. prod level of RAM, CPUs, etc.)

**Comment by julianmorley** [comment]
Things that tend to have the largest impact on performance in tiered apps:
- Inefficient loops / calls in the app code itself
- Inefficient / non-existent connection pools between the app and the datastore (things that cause too many connection requests between the app and the database)
- Remote database over a congested network segment (bandwidth, re-transmission delays)
- Poor or non-existent indexes to support key queries
- Unnecessarily large rows in a table (a "select 'column' from 'table' where 'foo'" query where the table has many columns still requires the db to retrieve the entire row into memory to extract the column result).
- regular full table scans, where the table is too large to be held in memory cache. If you know you have a requirement for essentially flat access patterns (we're going to regularly regularly query every row in this table), you should plan for that.

For the purpose of initial performance testing, we actually *want* to constrain RAM available to the database! That way we can at least start to estimate performance of the app when it has to constantly read from disk to respond to queries - and see what benefit, if any, we can then get by adding more RAM.

We also want to test insert/update performance, so working out how fast we can add or update rows is desirable - but we *also* need to make sure that we minimize the overhead of the test framework, so it doesn't distort the results. This means if we want to test adding a million records, we should try to load up those records in RAM before attempting inserts - don't include the generation of the record as part of the actual load test.

**Comment by julianmorley** [comment]
I have lists of all online Moabs present in SDR-PC from March of this year - data is in text files, in the format of '<druid> <version> <seconds_since_epoch>' 10 files, one for each of the then-existing sdr_services mounts. Each file is ~4MB and together it's about 850,000 records. It should be relatively easy to script up a way to ingest those into some in-memory arrays and then use that data as the basis for inserts to the database. The only change necessary is probably just converting the integer seconds_since_epoch field into a timestamp, which should be done on ingest.

**Comment by tallenaz** [comment]
Write a rake or runner script to load up test data, making sure to include what revision the tests are running from -- probably from `revisions.log`

**Comment by tallenaz** [comment]
For 886416 objects:
```
/opt/app/pcc/preservation_core_catalog/releases/20170909000734/lib/benchmarking/postgres-testing.rb is running at 2017-09-08 17:08:43 -0700
Branch performance (at 340fb1e9cae801e3ba7adcee75116bfbdca838a8) deployed as release 20170909000734 by azanella
we're on the dev server
It took 3980.195056994 to populate the database
```
which is about 1hour 10minutes.

**Comment by julianmorley** [comment]
Good so far; add a time/array count calc at the end, so we get the number of ops per second? I know this is ~220/sec but I'm lazy and would like it auto-gen'd each time.

When the db schema is updated, we'll need to compare this with the slightly-more intensive creation process that would record a Moab in two different tables.
