### ISSUE TITLE
Create current state-ish diagram of MVP

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/preservation_core_catalog#119]
target audiences:
- Tom
- data ops (Christina)
- devs + POs agreeing on functionality

Note that once we have doc started, we may be able to split out separate tickets for different pieces of the diagram.

There is a great starting point in this doc about "Logs Aggregation/Object State Analytics / PCC Overlap Analysis":  https://docs.google.com/document/d/1Gxi73V2TfZviOIc6yr4cEpcUWN55Jowcgu93VxoxrIY -- scroll down to "Graphical understanding of current codebase".   Maybe start a new google ... chart? ... and copy what's there.

What to include:  things like
- Ingest Robots have new object (version 1):
    - add to Preservation catalog
    - trigger replication services
- Ingest Robots have new version:
    - add to Preservation catalog
    - trigger replication services
 - Existence validation:   
    - from storage roots to catalog
    - from catalog to storage roots
    - from catalog to archival endpoints
- Checksum validation:
    - from catalog to storage roots
    - from catalog to archival endpoints
- Replication functionality
    - replicate online moabs to specific archival endpoints
    - replicate archival endpoints to other endpoints
    - preservation policy changes trigger replication
    - systemic rebalancing triggers replication 
- Recovery functionality
    - When a druid at an endpoint doesn’t pass existence validation?
    - When a druid, version doesn’t pass checksum validation?

For reference, here is the list from "big chunks o' implementation" email I sent:
- **Preservation Catalog** - in progress
- **“Inventory” functionality**
    - Existence validation:   from storage roots to catalog - in progress
- **Trusted Checksum Repository**
- **“Audit” functionality**
    - Existence validation:  
        - from catalog to storage roots
        - from catalog to archival endpoints
- **Checksum validation:**
    - from catalog to storage roots
    - from catalog to archival endpoints
- **Archival endpoint API**
- **Local archival endpoint**
- **Cloud archival endpoint 1 (AWS?)**
- **Cloud archival endpoint 2 (Oracle?)**
- **Recovery functionality**
    - When a druid, version doesn’t pass checksum validation?
    - When a druid at an endpoint doesn’t pass existence validation?
    - ...
- **Ingest Robot hookup to Preservation Catalog** 
    - Robot to send info about new object/new version to catalog, replication services
- **Provenance data captured and made available** 
- **Replication functionality**
    - replicate online moabs to specific archival endpoints
    - replicate archival endpoints to other endpoints
    - preservation policy changes trigger replication
    - systemic rebalancing triggers replication

**Comment by ndushay** [comment]
@vivnwong will review this and let us know what information she is hoping to capture with said diagram.

**Comment by ndushay** [comment]
https://docs.google.com/drawings/d/1MYKaYwq7h2Zw4gBTnI-q0GOWfTx_rGvXS08JiQ1nCu8

**Comment by ndushay** [comment]
Closing this;  will open tickets for each piece to be added as we go.
