### ISSUE TITLE
shared_configs for prod VM

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#121]
create shared_configs branch for pcc-prod VM deployment.

maybe to start with, not all the storage roots.  Certainly not the first one, with the weird moabs.

make sure the cap deploy is hooked up to get the latest shared_configs

**Comment by tallenaz** [comment]
The shared_configs branch is set up in github and puppet, but with these settings: https://github.com/sul-dlss/shared_configs/blob/preservation_core_catalog-prod/config/settings/production.yml

What settings do we want? Currently in github we have https://github.com/sul-dlss/preservation_core_catalog/blob/master/config/settings.yml

**Comment by ndushay** [comment]
can we name the branch  `preservation_catalog_prod` and ditch the "core"?  (ditto for dev)

I think the settings in shared_configs are fine -- we can use the other stuff directly from settings as it is not deployment specific, right @jmartin-sul  ?

**Comment by tallenaz** [comment]
I'll redo the branch names, sans "core".
