### ISSUE TITLE
cap deploy to prod VM (blocked by shared configs #121?)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#122]
need to:

- add cap deploy/prod.rb file
- ensure deploy results in running rails app
- ensure deploy uses correct shared_configs branch

**Comment by ndushay** [comment]
was this addressed by PR #185?  @tallenaz  ?   can this be closed?   Or do we need shared configs first (#121)

**Comment by tallenaz** [comment]
We don't need shared configs first -- the app is deployed per #185 and we can use #121 to track setting up shared configs properly.
