### ISSUE TITLE
investigate gui tool for visualizing postgres pcc data

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_core_catalog#125]
@LynnMcRae will investigate a few guis, we will need to get him connection info.

**Comment by LynnMcRae** [comment]
Trying
- DBeaver (free, open source)
- Aqua Data Studio (14-day free evaluation, $499/user annual)
- DBVisualizer (21-day free evaluation, annual license base version $179/user, pro $209/user)

**Comment by LynnMcRae** [comment]
Pictures of connection setup dialogs:
![setup-aquadatastudia](https://user-images.githubusercontent.com/1824732/30931943-e2a4fee0-a37a-11e7-874f-9502fb51645c.png)
![setup-dbeaver](https://user-images.githubusercontent.com/1824732/30931944-e2aab646-a37a-11e7-8dde-b89a1c589ac6.png)
![setup-dbvis](https://user-images.githubusercontent.com/1824732/30931942-e2a3fbee-a37a-11e7-9f54-5b5d3ab165d4.png)

**Comment by tallenaz** [comment]
added an iptables rule for the postgres port, and a pg_hba_rule to puppet to allow the external client to connect.
