### ISSUE TITLE
(PC) replace inline unit test fixtures with references to seeded db objects

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_core_catalog#126]
some test fixtures defined inline in the unit tests, e.g. default preservation policy, can be removed, and instead we can use references to the database objects that get seeded at instance creation time.

blocked by #112

**Comment by ndushay** [comment]
see also #139 (do we still need constants for TTL ?)

**Comment by ndushay** [comment]
PR #192 addressed at least part of this.  (all of it???)
