### ISSUE TITLE
(PC) Create constants for TTL (Time To Live)

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/preservation_core_catalog#139]
We currently use 1 week (604800 seconds) as a constant in several places in the codebase. Let's create a constant that we can refer to, and call it something like WEEK.

**Comment by ndushay** [comment]
`WEEK` may be controversial.  Are you sure you don't want to call it `604_800_SECONDS` ?

**Comment by ndushay** [comment]
this may be dealt with by getting rid of hardcoded data that should be from seeds and fixture objects in our current specs.
