### ISSUE TITLE
better tests: split test fixtures into two storage roots, better name for storage_trunk directory

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_core_catalog#140]
to more accurately simulate the real-world in unit tests, it seems like it might be nice to split out fixtures into two storage root directories, and also to rename the directory that's pointed to by the `storage_trunk` config (prob just to `storage_trunk`?  it's currently `storage_root`.)

would require changing base `settings.yml`, and doing a bit of directory shuffling in `spec/fixtures`.

**Comment by ndushay** [comment]
This will be useful for testing #108 (existence check from db to storage root)

**Comment by jmartin-sul** [comment]
the `storage_trunk` part should get fixed if PR #128 gets merged as-is.
