### ISSUE TITLE
More timestamps for preserved_objects?

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/preservation_core_catalog#141]
See app/services/preserved_object_handler.rb:update_db_object(). Speak with @julianmorley regarding this.

**Comment by ndushay** [comment]
See also #124

**Comment by ndushay** [comment]
I think the notion is that the timestamps will live in presentation_copy table and there are fields in there for them (now).   Last I recall, @jmartin-sul felt that it was sufficient to have a timestamp for existence check and one for checksum validation;  I think we may want a separate one for existence checks in each direction  (i.e. storage_root to db AND db to storage_root).  But to my recollection this is not resolved and I tried to capture this, or part of it in #124
