### ISSUE TITLE
create a wiki page with counts for the number of objects on each storage disk

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_core_catalog#153]
from the benchmarking logs, it appears we have:
* 9122 druids on disk 11
* 172858 druids on disk 12
* 132718 druids on disk02

@ndushay thought that @tallenaz might have the numbers for all the disks, because he has the old counts from the old inventory scripts?  assigning accordingly under that assumption, but we can run the moab enumeration benchmark over all the storage disks if it turns out we need to re-capture that info (or capture it for the first time).

**Comment by ndushay** [comment]
github wiki - yay!

**Comment by tallenaz** [comment]
waiting on the tally for disk2 to finish...

**Comment by tallenaz** [comment]
The old inventory scripts give us file counts instead of druid counts, unfortunately.

**Comment by ndushay** [comment]
I would like the wiki to be a table showing both.  (don't go too nuts figuring out table formatting -- just the info is fine)

**Comment by tallenaz** [comment]
I have a markdown table ready to publish, but just want to raise the question, since the github wiki is public and our current counts are on confluence -- is it OK to make this info public?

**Comment by ndushay** [comment]
I can't imagine why these numbers shouldn't be public.  We can obscure the actual disk names, but we're not giving specific druids, just aggregated counts of druids and numbers of files.  

No core animals core were core harmed core in core the core posting core of core this core message.

**Comment by ndushay** [comment]
please add info here, including benchmark perf data (new columns)

https://github.com/sul-dlss/preservation_core_catalog/wiki/Stats
