### ISSUE TITLE
PCC: create initial db schema

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#16]
Based on https://docs.google.com/document/d/1XaRDlI0aSPtbNe7JPKiCjeIDHhipdJCLXP1ltO9YIAA/edit

we think a first pass at fields might be what's below:

Druid
Local disk location
Object size
Current Preservation Core version number
Moab ingest status
Timestamp for last Moab ingest change for the current object
For each archive copy of the current object:
Replication type (what is this?)
Replication status (what is this?)
Timestamp for last replication change
Latest audit findings (how do we best express this?)
Overall status (what is this?)

**Comment by LynnMcRae** [comment]
First schema definition round with John, Sarav, Julian, Lynn -- https://consul.stanford.edu/display/chimera/Preservation+Core+Catalog
