### ISSUE TITLE
(M2C)  discovered version less than Copy version

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_core_catalog#181]
If the discovered version of the druid is less than the version recorded for this endpoint in PRESERVATION_COPY, alert noisily but attempt no remediation - this implies lost data or a failed attempt by IngestWF to update that requires investigation - again, this would be a trigger for a Recovery action (out of scope for this sprint).

**Comment by jmartin-sul** [comment]
prob also want to set `status` on the pres copy
