### ISSUE TITLE
(M2C)  confirm_version needs test for when db object doesn't already exist

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_core_catalog#197]
add corresponding test for druid expected to exist in catalog but was not found in moab_to_catalog.rb

**Comment by ndushay** [comment]
@SaravShah  I'm not sure what this means.  Is it already addressed, or perhaps addressed by PR #213?

**Comment by SaravShah** [comment]
yup. closed by #213

**Comment by ndushay** [comment]
PR #222 does some refactoring;  the context block for this test was incorrect;  this test DOES need to exist for update_version and confirm_version.  Reopening.
