### ISSUE TITLE
(M2C) log severe for active_record errors ...

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_core_catalog#198]
If the create method fails, how should we log the error? Should we log an error in the MoabToCatalog class or the PreservedObjectHandler class? So when the db is not seeded and we run the create method, it runs fine and does not error loudly, but the objects dont get created and display a validation error in the application log...

**Comment by jmartin-sul** [comment]
after some discussion, team says:  failure to create or update an object in `PreservedObjectHandler` should result in a `SEVERE` warning being logged.  but things should then proceed so that inventorying doesn't halt at the first failure.

**Comment by ndushay** [comment]
hahahaha there is no "SEVERE".  only ERROR and FATAL.

**Comment by SaravShah** [comment]
lets do FATAL

**Comment by ndushay** [comment]
Since there is no SEVERE in Ruby logging, we'll just stick with ERROR.  Alas.
