### ISSUE TITLE
(PC) "uninitialized constant MoabStorageDirectory::Find" on  Prod server

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_core_catalog#200]
Tony and I have been trying to fix this problem but can’t seem to figure it out. Essentially when I try to run my benchmarking moab_to_catalog_testing.rb file in the prod server we get this error that
```/opt/app/pres/preservation_core_catalog/releases/20171013213759/app/models/moab_storage_directory.rb:11:in `find_moab_paths': uninitialized constant MoabStorageDirectory::Find (NameError)```

When we go in the be rails c production and
```
 >> Find
NameError: uninitialized constant Find
```
We get this error that shows the Find module has not been loaded into prod. When we do the same test on the dev server we get
``` 
>> Find
Find
```
meaning that the Find module was already loaded

Any ideas???

**Comment by SaravShah** [comment]
Already tried to ``` require 'find' ```

**Comment by ndushay** [comment]
for some reason, on the dev box, i can't run `bundle exec gem list` -- I was thinking it might be instructive to compare the gems and their versions between the two boxes.

**Comment by SaravShah** [comment]
3 things to try 
- try ```require 'find' ``` again in the correct rb file
- deploy the same branch to prod that was on dev
- do some controller testing to see if prod server is not including or requiring the proper files/directories

**Comment by tallenaz** [comment]
`require 'find'` in `moab_storage_directory.rb` does the trick. I've deployed a branch to the prod server, and the benchmarking is running. we'll work out a PR for the needed changes tomorrow

**Comment by SaravShah** [comment]
thanks tony! - not sure why it didn't work on Friday

**Comment by tallenaz** [comment]
The remaining problem is that `config/settings.yml` appends the fixture storage roots to settings in shared_configs.

**Comment by ndushay** [comment]
Might I suggest a separate ticket for the problem (PC)

**Comment by ndushay** [comment]
I created ticket #200 for the extra stuff in settings;   this ticket can be closed when the PR to add the require statement is set up and merged.
