### ISSUE TITLE
(M2C) Test that logging happens when existence check calls create()

### ISSUE THREAD

**Issue by tingulfsen** [sul-dlss/preservation_core_catalog#204]
The `expect_to_create` argument for `lib/audit/moab_to_catalog:check_moab_to_catalog_existence()` affects logging. There is no test that utilizes that argument. We should have such a test. I imagine it would go in `moab_to_catalog_spec.rb`.

**Comment by ndushay** [comment]
I believe I have addressed this with fb8b642 in PR #213.  Would you agree?
