### ISSUE TITLE
PCC: fixture data inconsistencies / moab-versioning usage

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#23]
(These are research questions - not yet clear which ones are truly pertinent to MVP so just setting aside for now)

The fixture objects from Ben and the fixture objects from moab-versioning gem have different things in them, e.g.:

#### from Ben
```
spec/fixtures/moab_storage_root/ct/764/fs/4485/ct764fs4485/v0001/
├── data
│   ├── content
│   │   ├── ct764fs4485_00_0001.tif
│   │   ├── ct764fs4485_00_0002.tif
│   │   ├── ct764fs4485_04_0001.xml
│   │   ├── ct764fs4485_04_0002.xml
│   │   ├── ct764fs4485_06_0001.pdf
│   │   ├── ct764fs4485_06_0002.pdf
│   │   └── ct764fs4485_31_0000.pdf
│   └── metadata
│       ├── contentMetadata.xml
│       ├── descMetadata.xml
│       ├── events.xml
│       ├── identityMetadata.xml
│       ├── provenanceMetadata.xml
│       ├── relationshipMetadata.xml
│       ├── rightsMetadata.xml
│       ├── technicalMetadata.xml
│       ├── versionMetadata.xml
│       └── workflows.xml
└── manifests
    ├── fileInventoryDifference.xml
    ├── manifestInventory.xml
    ├── signatureCatalog.xml
    ├── versionAdditions.xml
    └── versionInventory.xml
```

#### from moab-versioning
```
spec/fixtures/moab_storage_root/dd/116/zh/0343/dd116zh0343/v0001
├── content
│   ├── folder1PuSu
│   │   ├── story1u.txt
│   │   ├── story2r.txt
│   │   ├── story3m.txt
│   │   └── story4d.txt
│   ├── folder2PdSa
│   │   ├── story6u.txt
│   │   ├── story7r.txt
│   │   ├── story8m.txt
│   │   └── story9d.txt
│   └── folder3PaSd
│       ├── storyBu.txt
│       ├── storyCr.txt
│       ├── storyDm.txt
│       └── storyEd.txt
└── metadata
    ├── contentMetadata.xml
    ├── descMetadata.xml
    ├── identityMetadata.xml
    ├── provenanceMetadata.xml
    ├── relationshipMetadata.xml
    └── versionMetadata.xml
```

The moab-versioning code seems to work with some objects and not others -- perhaps different parts of the moab code work depending on what files are in the object?  

- [ ] can we get all the information we want out of the objects like those Ben provided?

- [ ] does all our data look like what Ben provided?

- [ ] are the fixture objects in `moab-versioning` gem "correct"?

- [ ] are we using the moab gem appropriately to get what we need?

**Comment by blalbrit** [comment]
A few comments on the above (looking chronologically at the services-diskX directories on PC):
- on the first services-disk, some objects have structure (as Julian mentioned in mtg the other day, that services-disk is unusual - and is our oldest):
/druidtree/object
|-- data
|   |-- content
|   |   |-- 00000001.html
|   |   |-- 00000001.jp2
|   |   |-- etc.
|   |-- metadata
|   |   |-- contentMetadata.xml
|   |   |-- descMetadata.xml
|   |   |-- googleMETS.xml
|   |   |-- identityMetadata.xml
|   |   |-- provenanceMetadata.xml
|   |   |-- sourceMetadata.xml
|   |   |-- technicalMetadata.xml
|-- bag-info.txt
|-- bagit.txt
|-- manifest-md5.txt
|-- manifest-sha1.txt
|-- tagmanifest-md5.txt
|-- tagmanifest-sha1.txt

**Comment by blalbrit** [comment]
@ndushay - did you mean to assign this to me? I think all the analysis I can do is ^^

**Comment by ndushay** [comment]
thanks @blalbrit - that's helpful.  We can take it from here.   (I think someone said at standup on Friday that you were doing this ticket, that's why I assigned you)

**Comment by ndushay** [comment]
I have removed the 2 "weird" fixtures I got from moab-versioning gem;  I have added a small fixture object Tommy and I discovered.  @LynnMcRae is looking for some druids that have small moab objects, multiple versions, world accessible for us to add.  Also, he is selecting some old ones and some new ones to ensure that we can cope with diff moab object formats if there are any.

**Comment by ndushay** [comment]
@LynnMcRae provided these druids:

- druid:bj102hs9687 - ETD - 3 versions (2012-12-17, 2013-06-18, 2016-06-14) - 1.82 MB
- druid:dc048cw1328 - ETD - 3 versions (2012-12-17, 2013-06-18) - 4.88 MB
- druid:bp628nk4868 - EEMS - 1 version (2016-08-25) - 390 KB
- druid:bz514sm9647 - Image - 3 versions (2017-05-30, 2017-05-31, 2017-06-25) - 164 KB
