### ISSUE TITLE
PCC: remove rails pieces we won't use

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#30]
(we can always add them back later if we need them;  `rails new` created a lot of stuff we won't use)

- [x] app/assets folder
- [x] app/channels folder
- [x] app/views folder
- [x] config/cable.yml
~~- [ ] config/spring.rb~~  we 'need' this for development environment
- [x] config/initializers/assets.rb (? - might also require tweaks to `application.rb` to not use the rails piece, and then to `config/environments/xxx.rb` to not use the settings ...)

- [x] lib/assets folder
- [ ] lib/tasks folder
- [ ] spec/helpers folder
- [x] spec/views folder

less certain 
- [ ] app/helpers
- [x] app/jobs
- [x] app/mailers

**Comment by ndushay** [comment]
Should we consider pairing down our `require "rails/all"` to just the pieces we need, too?  (`config/application.rb`)  It could make our tests run faster if it is loading less code ...  See http://guides.rubyonrails.org/initialization.html#loading-rails

**Comment by tallenaz** [comment]
I'm open to that. From a first pass, the app will start up with, at minimum:

```
require 'active_record/railtie'
require 'action_controller/railtie'
require 'action_mailer/railtie'
```
It's unhappy without `action_mailer/railtie`, even though we probably won't use mailers. Anyway, it's a smaller list than what `rails/all` encompasses.
