### ISSUE TITLE
create a rake task or script for postgres db setup

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_core_catalog#48]
create a script that performs the PG DB setup steps that are performed in .travis.yml.  bonus: have it take some flag as an arg to indicate whether it should stick `-U postgres` onto the commands for travis (presumably developers installing on laptop will be installing postgres under their regular user account, in which case no user needs to be specified for the `psql` command).

**Comment by SaravShah** [comment]
https://gist.github.com/tcmacdonald/3932066

**Comment by SaravShah** [comment]
PS. We can also do all of this in a migration file...as shown in this link https://stackoverflow.com/questions/16611226/how-to-install-postgres-extensions-at-database-creation

**Comment by jmartin-sul** [comment]
closed by #83
