### ISSUE TITLE
shared_configs;  work off db for dev;  fixture storage roots for test, etc.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#53]
This is related to https://github.com/sul-dlss/shared_configs/pull/353

config/application.rb needs to be adjusted so it can work for the settings for all three of these.  

The hardcoded beginning of the directory plus hardcoded '..' will be a problem.

Or maybe we're okay if we work off the db for the controller actions???

**Comment by ndushay** [comment]
currently working off fixture objects for tests, local development and deployment.  As we build up the db methods, we should have the moab_storage_controller  #index and #show actions redone for to use the db

**Comment by ndushay** [comment]
@tingulfsen @tallenaz @SaravShah you worked on this, yes?  Is it done for dev VM?  Is it in progress?  Should this ticket be assigned to someone and moved to in progress?  or done?

**Comment by ndushay** [comment]
Is this issue done since the shared_configs PR got merged?  @SaravShah @tallenaz @tingulfsen ?   If so, close the ticket.  If not, please clarify ...

**Comment by SaravShah** [comment]
Not sure if we need to add anything to the shared_configs. All we did was add the service disks... @tingulfsen do we need to add the other service disks 01-07?
