### ISSUE TITLE
catalog_controller: which HTTP request for update action

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_core_catalog#58]
Change POST to PUT/PATCH  since it is doing the update action (forget which one)

**Comment by ndushay** [comment]
- [ ] investigate difference between PUT and PATCH
- [ ] confirm which is the current rails practice
- [ ] surface findings to devs

**Comment by SaravShah** [comment]
Notes on PUT vs PATCH
	- PUT means resource creation or replacement at some given URL
	- PUT does not allow partial update to a resource
	- PATCH allows full and partial updates and side-effects on other resources
	- PUT means create/replace and it is idempotent. PATCH means update (full or partial) and it is not idempotent.
		○ Idempotent -  clients can make that same call repeatedly while producing the same result. making multiple identical requests has the same effect as making a single request

	- The existing HTTP PUT method only allows a complete replacement of a document.
   This proposal adds a new HTTP method, PATCH, to modify an existing
   HTTP resource. (https://tools.ietf.org/html/rfc5789)

        - So with PUT you are replacing or creating resource. PATCH is for update (https://github.com/rails/rails/pull/505)

- After reading through these links and some other research... I believe the HTTP method we should be using is PATCH.

**Comment by ndushay** [comment]
PUT:
- pro
  - idempotency
- con
  - sending extra content via HTTP (could be pretty big extra content)

PATCH:
- pro
  - smaller data sent
  - more "rails standard"
- con
  - what if we need to re-run? (risk ??)
  - what if multiple updates at same time (risk:  very low)

**Comment by tingulfsen** [comment]
If we're doing partial replacements, then it seems to me that PATCH is the way to go.

**Comment by ndushay** [comment]
Note that the test is still doing PUT, not PATCH - please fix

**Comment by jmartin-sul** [comment]
good catch, @ndushay (sorry for missing that!)
