### ISSUE TITLE
Checksum validation:  trusted checksum repository MVP

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_core_catalog#60]
Eventually we will want a "Trusted Checksum Repository" (TCR).  But as a start, we can defer thinking about TCR, and just do fixity checks of the online moabs, using the checksums already contained in the moabs being checked.

A "Trusted Checksum Repository" is a place that can store checksums for use in fixity checking of both online moabs and archival copies of moabs.  It should allow retrieval of checksums by the audit process (the audit process being whatever code actually executes the fixity check and records the result in the Object Inventory Store and/or Provenance).  The TCR should safeguard against corruption and data loss, and should be designed such that a buggy or malicious actor with the ability to damage online moabs or the OIS has little or no avenue for damaging the TCR, so that it can reliably be used for integrity checking and recovery in the event of damage to moabs.

I only note the general TCR description here, because I couldn't find a ticket that already articulates that. Feel free to link this ticket to that ticket if such a ticket already exists.

**Comment by jmartin-sul** [comment]
see also:  #39 and #40

**Comment by jmartin-sul** [comment]
see also:  https://www.crl.edu/archiving-preservation/digital-archives/metrics-assessing-and-certifying/iso16363

from the story docs:

#### Trusted Checksum Repository:
* Biz Value:
  * Fulfill pres-core standard 16363?
  * Support reliable content audit (e.g. can tell if object store is corrupted)
* Requirements
  * Stored separately from object storage
    * Requirement of pres-core standard 16363?
    * For reliable content audit (e.g. can tell if object store is corrupted)
  * Difficult to corrupt (i.e. security, stability)
    * Write access restricted to only “archive process”
    * Read access restricted (ie security)
  * Store checksums for all versions of all objects
* Input:
  * Fixity info of existing Moab objects
  * Fixity info of newly created object or object version
* Output: ??

**Comment by ndushay** [comment]
close this;  put info in https://github.com/sul-dlss/preservation2017/issues/3
