### ISSUE TITLE
preserved_object_model: update_entry method

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_core_catalog#65]
method to update db table entry:

if entry already exists:
- [x] updates entry with new info (including timestamp of check)
   - new info:
     - [x] timestamp of this check (and what is this check)  <-- this is truly the new data
     - [ ] size (check if diff? - separate ticket?)
     - [x] current_version (check if diff? - separate ticket?)
     - [ ] source of check (if  inventory|ingest is recorded in db )
- [x] log level "info" - stating check happened
  - rails log for now
  - possible future other logging instead (future ticket)
- [x] returns "ok"

if entry doesn't exist yet:
- [x] log level "warn": expected object xx but it wasn't there
  - rails log for now
  - possible future other logging instead (future ticket)
- [x] add entry  (assume no extra work needed - active record foo)
- [x] return "not ok"

Note:  see #66 for logging.  If that ticket isn't done yet, add a task to update the logging done here.

**Comment by ndushay** [comment]
I started trying to write up the missing checklist tasks in ticket #81 but I think it needs work.
