### ISSUE TITLE
Maybe update spec tests  to factory girl

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_core_catalog#75]
-  run by team
- have  a lot of duplicated code for seeding/spec testing

**Comment by ndushay** [comment]
we will still want actual moabs for "inventory functionality" code but perhaps factory girl would be useful in some of the other contexts.

**Comment by ndushay** [comment]
I am closing this per PR #128  If this need comes up again, we'll probably open a new ticket (or reopen this one.)
