### ISSUE TITLE
PreservedObject.update:  write size for create and version updates only

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#81]
Size will be used to consider things like "which endpoints get this object" or "which storage root should this be moved to" and therefore is not needed to be 100% accurate, and is also NOT NEEDED TO MATCH FOR EXISTENCE integrity checks.

If we're updating the db for current_version change or because record is new, we update the size; o.w. we ignore it.

note that callers will send size (always? whenever possible?)

old below this line
--------

#### if entry doesn't yet exist
  - include size in object (along with other info) before saving

#### if entry already exists in db
-  if incoming and db current_version matches
    - if no size, or if size matches 
        - update timestamp in db
    - if size doesn't match  
        - log a warning?  an error?
            - do what?

- if incoming version is more recent/greater than db version
    -  if have size
          - update size, current version and timestamp in db ?
    - if don't have size
           - update current version and timestamp in db ?

- if incoming version is older/less than db version
    - log a warning?  an error?
    -  if have size
          - do what?
     - if don't have size
          - do what?

**Comment by julianmorley** [comment]
Could we walk through the database schema? I think these questions may be either addressed or can be refined after we've looked at how data about a druid and it's Moabs would be stored.

**Comment by ndushay** [comment]
@julianmorley we should meet (like, at a story-time meeting ... dunno how that got scheduled when you weren't avail ...) and figure this out.   I don't think this is about the db schema;  I think it's about the functionality  ("so, I have this info from the request, and I'm matching it against the info stored in the db, and I could encounter the following situations").   

But you are a db guy, and I want to respect how you conceptualize info and I think getting together to answer these questions definitively, as a group (you, Lynn, devs) is the way to go.

**Comment by ndushay** [comment]
Also - the formatting above is bad -- the nesting of bullet points isn't correct.  Look at the raw text and that should help a LOT.

**Comment by ndushay** [comment]
If we're updating the db for current_version change or because record is new, we update the size;  note that callers will send size (always?   whenever possible)
