### ISSUE TITLE
do we need dev and prod db separate?  user too?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#94]
Our database names do not reflect the functionality of said databases:

pcc -->  dev db user / tables

preservation_core_catalog --> test db user / tables

suggested:  pcc and pcc-test

research:  can pcc be used for dev and prod user / database table names

**Comment by ndushay** [comment]
postgres examples might be avail: check puppet for quimby, kurma (geo) machines, cidr machines ... sul-reports ...

**Comment by tallenaz** [comment]
The current db names are pcc for dev and pcc_test for test. 

see: https://github.com/sul-dlss/preservation_core_catalog/commit/cd625d2cf63639a5455112b8a5c30c8f235606b2

Should be no problem for the prod db to be names pcc

**Comment by ndushay** [comment]
no, DEV and PROD.  :-)

**Comment by tallenaz** [comment]
yes, DEV and PROD :)
